---
- name: Ensure all dehydrated dependencies are installed
  pacman:
    pkg: "{{ packages }}"
    state: present
  vars:
    packages:
    - openssl
    - curl
    - sed
    - grep
    - coreutils
    - cronie
  tags:
    - dehydrated

- name: Make sure cronie is running
  service:
    name: cronie
    state: started
    enabled: true
  tags:
    - dehydrated
