---
- name: Ensure all dehydrated dependencies are installed
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:      
    - openssl
    - curl
    - sed
    - grep
    - coreutils
  tags:
    - apt
    - dehydrated
