---
- name: Ensure that the letsencrypt challenge directory exists
  file:
    path: "{{ dehydrated_well_known_path }}/.well-known/acme-challenge"
    state: directory
    mode: 0755
    owner: root
  tags:
    - dehydrated

- name: Ensure that the letsencrypt cert directory exists
  file:
    path: "{{ dehydrated_cert_path }}"
    state: directory
    mode: 0755
    owner: root
  tags:
    - dehydrated

- name: include install tasks
  include_tasks: install_{{ ansible_distribution|lower }}.yml
  tags:
    - dehydrated

- name: Ensure that the dehydrated configuration exists
  template:
    src: dehydrated.conf
    dest: "{{ dehydrated_cert_path }}/dehydrated.conf"
  tags:
    - ssl

- name: Ensure that the dehydrated hooks file exists
  template:
    src: hooks.sh
    dest: "{{ dehydrated_cert_path }}/hooks.sh"
    mode: 0750
    owner: root
  tags:
    - dehydrated

- name: Ensure that the dehydrated deploy_hooks folder exists
  file:
    path: "{{ dehydrated_deploy_hook_directory }}"
    state: directory
    mode: 0750
    owner: root
  tags:
    - dehydrated

- name: Ensure that the letsencrypt domain list file exists
  file:
    path: "{{ dehydrated_cert_path }}/domains.txt"
    state: touch
  tags:
    - dehydrated

- name: Build the letsencrypt domain list
  template:
    src: domains.txt.j2
    dest: /etc/ssl/letsencrypt/domains.txt
  tags:
    - dehydrated

- name: Download the dehydrated shell script
  get_url:
    url: https://raw.githubusercontent.com/lukas2511/dehydrated/v0.6.1/dehydrated
    dest: /etc/ssl/letsencrypt/dehydrated
    mode: 0700
    sha256sum: fa4a788e244b61a69f091a19430821a616de2fc1ab1be237aa15973848178fcf
  tags:
    - dehydrated

- name: Accept the Terms of Service if nessesary
  command: ./dehydrated --register --accept-terms
  args:
    chdir: "{{ dehydrated_cert_path }}"
  tags:
    - dehydrated

- name: Execute dehydrated shell script
  command: ./dehydrated -c --hook {{ dehydrated_cert_path }}/hooks.sh -f {{ dehydrated_cert_path }}/dehydrated.conf
  args:
    chdir: "{{ dehydrated_cert_path }}"
  tags:
    - dehydrated

- name: Add letsencrypt cronjob
  cron:
    name: letsencrypt
    hour: 7
    minute: 0
    day: "*/3"
    job: "{{ dehydrated_cert_path }}/dehydrated -c --hook {{ dehydrated_cert_path }}/hooks.sh -f {{ dehydrated_cert_path }}/dehydrated.conf"
    cron_file: ansible_dehydrated
  tags:
    - dehydrated
